first_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
# Create your views here.
app_name = "first_app"
urlpatterns = [
	url(r'^$', views.homepage, name = 'homepage'),
    url(r'^organisms/', views.organisms, name = 'organisms'),
    path(r'^organism_search/<str:organism>/', views.org_search, name='org_search'),
    path(r'^org_list_by_abc/<str:first_letter>/', views.org_list_by_abc, name='org_list_by_abc'),
    path(r'^pfam_search/<str:pfam>/', views.pfam_search, name='pfam_search'),
    ]

toxins_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from first_app import views
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('first_app.urls'))
]

first_app/models.py
from django.db import models

# Create your models here.
class Genomes(models.Model):
    genome_id = models.CharField(max_length = 264, unique = True, primary_key=True)
    organism_name = models.CharField(max_length = 264)
    #scaffold = models.CharField(max_length = 264, unique = True, primary_key=True)
    def __str__(self):
        return self.genome_id
class Genes(models.Model):
    genome_id = models.ForeignKey(Genomes, on_delete = models.CASCADE )
    gene_id = models.CharField(max_length = 264, unique = True, primary_key=True)
    scaffold = models.CharField(max_length = 264)
    gene_len = models.IntegerField()
    start = models.IntegerField()
    end = models.IntegerField()
    strand = models.CharField(max_length = 1)
    product_name = models.CharField(max_length = 264)
    protein_toxicity = models.CharField(max_length = 264)
    def __str__(self):
        return self.gene_id
class Pfams(models.Model):
    pfam_id = models.CharField(max_length = 264, unique = True, primary_key=True)
    pfam_name = models.CharField(max_length = 264)
    pfam_len = models.IntegerField()
    toxic_id = models.CharField(max_length = 264)
    def __str__(self):
        return self.pfam_name
class PfamsInGenes(models.Model):
    id = models.BigAutoField(primary_key=True)
    gene_id = models.ForeignKey(Genes, on_delete = models.CASCADE)
    organism_name = models.CharField(max_length = 264)
    pfam_id = models.ForeignKey(Pfams, on_delete = models.CASCADE)
    toxic_id = models.CharField(max_length = 264)
    pfam_start = models.IntegerField()
    pfam_end = models.IntegerField()
    # bit_score = models.FloatField()
    # e_val = models.CharField(max_length = 264)
    def __str__(self):
       return str(self.id)

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Genomes, Genes, Pfams, PfamsInGenes
from django.core.paginator import Paginator
from django.db.models.functions import Lower
from dna_features_viewer import GraphicFeature, GraphicRecord, CircularGraphicRecord
from io import *
import base64
import random
# Create your views here.
def random_color():
    r = random.randint(0, 0)
    g = random.randint(120, 255)
    b = random.randint(120, 255)
    rand_color = (r/256, g/256, b/256)
    return rand_color
def organisms(request):
    organism_list = []
    organisms = Genomes.objects.order_by(Lower('organism_name').asc())
    organism_list = organisms.values_list("organism_name", flat = True)
    #pfams = Pfams.objects.order_by(Lower('pfam_name').asc())
    #pfams_list = pfams.values_list('pfam_name',flat=True)
    my_dict = {"organism_list":organism_list, "abc": [c for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"]}

    return render(request, 'first_app/organisms.html', context = my_dict)
def homepage(request):
    organism_list = []
    organisms = Genomes.objects.order_by(Lower('organism_name').asc())
    organism_list = organisms.values_list("organism_name", flat = True)
    pfams = Pfams.objects.order_by(Lower('pfam_name').asc())
    pfams_list = pfams.values_list('pfam_name',flat=True)
    my_dict = {"organism_list":organism_list, "pfams_list":pfams_list}
    return render(request, 'first_app/toxin-base.html', context = my_dict)
def org_search(request, organism):
    org = Genomes.objects.filter(organism_name__exact = organism)

    org_id_values = org.values("genome_id")

    genes_ids = Genes.objects.filter(genome_id__in = org_id_values).values_list('gene_id', flat = True)

    pfams = PfamsInGenes.objects.filter(gene_id__in = genes_ids)

    genes_list = pfams.values_list('gene_id', flat = True)
    paginator = Paginator(pfams, 25) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    GraphicRecord.labels_spacing = 1
    graphic_pfams_toxins = [GraphicFeature(start = int(pfams[i].pfam_start), end = int(pfams[i].pfam_end), strand = +1, color = random_color(), label = str(pfams[i].pfam_id)) for i,p in enumerate(pfams) if str(pfams[i].toxic_id)=="tox"]
    graphic_pfams_anti = [GraphicFeature(start = int(pfams[i].pfam_start), end = int(pfams[i].pfam_end), strand = +1, color = random_color(), label = str(pfams[i].pfam_id)) for i,p in enumerate(pfams) if str(pfams[i].toxic_id)=="anti-tox"]



    record_tox = GraphicRecord(sequence_length=10000, features=graphic_pfams_toxins)
    record_anti = GraphicRecord(sequence_length=10000, features=graphic_pfams_anti)
    ax1, _ = record_tox.plot(figure_width=12, figure_height = 8)
    #ax1.set_title("toxins")
    buffer = BytesIO()
    ax1.figure.savefig(buffer, format='png')
    ax1.figure.tight_layout()
    buffer.seek(0)
    image_png = buffer.getvalue()
    buffer.close()

    graphic1 = base64.b64encode(image_png)
    graphic1 = graphic1.decode('utf-8')
    ax2, _ = record_anti.plot(figure_width=12, figure_height = 8)
    ax2.figure.tight_layout()
    #ax2.set_title("anti - toxins")
    buffer = BytesIO()
    ax2.figure.savefig(buffer, format='png')
    buffer.seek(0)
    image_png = buffer.getvalue()
    buffer.close()

    graphic2 = base64.b64encode(image_png)
    graphic2 = graphic2.decode('utf-8')
    my_dict = {'pfams': pfams, 'organism': organism, 'page_obj': page_obj, 'graph1': graphic1, "graph2": graphic2}
    return render(request, "first_app/organism_search.html", my_dict)
def pfam_search(request, pfam):
    pfam_ids = Pfams.objects.filter(pfam_name__exact = pfam).values_list('pfam_id', flat = True)
    genes_entries = PfamsInGenes.objects.filter(pfam_id__in = pfam_ids)
    gene_ids = genes_entries.values_list('gene_id')
    genome_ids = Genes.objects.filter(gene_id__in = gene_ids).values_list('genome_id', flat = True)
    organisms = Genomes.objects.filter(genome_id__in = genome_ids).values_list('organism_name', flat = True)

    paginator = Paginator(genes_entries, 25) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    my_dict = {"genes_with_pfam": genes_entries, "orgsnism_with_pfams": organisms, 'pfam':pfam, 'page_obj': page_obj}
    return render(request, "first_app/pfam_search.html", my_dict)
def org_list_by_abc(request, first_letter):
    org = Genomes.objects.filter(organism_name__startswith = first_letter.lower())
    org_names = org.values("organism_name")
    my_dict = {'org_list': org_names}
    return render(request, "first_app/org_list_by_abc.html", my_dict)

templates/first_app/org_list_by_abc.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>toxin base</title>
	<meta charset="utf-8" />

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
				integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href = "https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" >

	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>

</head>
<body class="body" style="background-color:#e6e6e6">
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="http://www.asaflevylab.com/#"><img src="http://www.asaflevylab.com/labimages/levy_logo.png" style='max-height:40px;'alt="Asaf Levy Lab Logo"></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<div class="navbar-nav">
					<a class="nav-item nav-link active" href="/toxin-base/"> Home </a>
				</div> <!-- /.navbar-nav, left-hand content -->
				<div class="navbar-nav ml-auto">
					<!-- SEARCH BAR -->
					<form class="form-inline" action="/genusearch" method="get">
						<input class="form-control mr-sm-2" name="q" type="text" placeholder="Gene ID" aria-label="Search">
						<button class="btn btn-outline my-2 my-sm-0" type="submit" style="color:green">SEARCH </button>
					</form>
				</div> <!-- /.navbar-nav, right-hand content -->
			</div> <!-- /.navbar-collapse -->
		</nav>
<div class="container-fluid" style="min-height:95%; ">
<br>
<ul class="" >
		{% for entry in org_list %}
			<li><a class="dropdown-item" href="{% url 'first_app:org_search' entry.organism_name %}">{{entry.organism_name}}</a></li>
			 {% endfor %}
</ul>
</div>
</html>

templates/first_app/organisms.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>toxin base</title>
	<meta charset="utf-8" />

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
				integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href = "https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" >

	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>

</head>
<body class="body" style="background-color:#e6e6e6">
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="http://www.asaflevylab.com/#"><img src="http://www.asaflevylab.com/labimages/levy_logo.png" style='max-height:40px;'alt="Asaf Levy Lab Logo"></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<div class="navbar-nav">
					<a class="nav-item nav-link active" href="/toxin-base/"> Home </a>
				</div> <!-- /.navbar-nav, left-hand content -->
				<div class="navbar-nav ml-auto">
					<!-- SEARCH BAR -->
					<form class="form-inline" action="/genusearch" method="get">
						<input class="form-control mr-sm-2" name="q" type="text" placeholder="Gene ID" aria-label="Search">
						<button class="btn btn-outline my-2 my-sm-0" type="submit" style="color:green">SEARCH </button>
					</form>
				</div> <!-- /.navbar-nav, right-hand content -->
			</div> <!-- /.navbar-collapse -->
		</nav>
    <div class="container-fluid" style="min-height:95%; ">
    <br>
    <h5> search for oganism by name</h5>
    <br>
    {% for entry in abc %}
    <!-- <div class="btn-group">
      <button type="button" class="btn btn-dark btn-sm dropdown-toggle" data-toggle="dropdown">{{entry}}<span class="caret"></span></button>
      <ul class="dropdown-menu scrollable-menu" role="menu" style = "height:auto;max-height: 500px;overflow-x: hidden;">
        {% for entry1 in org_list %}
          <li><a class="dropdown-item" href="{% url 'first_app:org_search' entry1 %}">{{entry1}}</a></li>
           {% endfor %}
      </ul>
  </div> -->
    <a class="btn btn-dark btn-sm" href="{% url 'first_app:org_list_by_abc' entry %}"role="button">{{entry}}</a>
    {% endfor %}
    <!-- <a class="btn btn-dark btn-sm" href="b_organisms/" role="button">B</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">C</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">D</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">E</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">F</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">G</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">H</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">I</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">J</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">K</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">L</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">M</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">N</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">O</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">P</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">Q</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">R</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">S</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">T</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">U</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">V</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">W</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">X</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">Y</a>
    <a class="btn btn-dark btn-sm" href="organisms/" role="button">Z</a> -->
</div>
</html>

templates/first_app/toxin-base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>toxin base</title>
	<meta charset="utf-8" />

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
				integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href = "https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" >

	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>

</head>
<body class="body" style="background-color:#e6e6e6">
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="http://www.asaflevylab.com/#"><img src="http://www.asaflevylab.com/labimages/levy_logo.png" style='max-height:40px;'alt="Asaf Levy Lab Logo"></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<div class="navbar-nav">
					<a class="nav-item nav-link active" href="/"> Home </a>
				</div> <!-- /.navbar-nav, left-hand content -->
				<div class="navbar-nav ml-auto">
					<!-- SEARCH BAR -->
					<form class="form-inline" action="/genusearch" method="get">
						<input class="form-control mr-sm-2" name="q" type="text" placeholder="product name" aria-label="Search">
						<button class="btn btn-outline my-2 my-sm-0" type="submit" style="color:green">SEARCH </button>
					</form>
				</div> <!-- /.navbar-nav, right-hand content -->
			</div> <!-- /.navbar-collapse -->
		</nav>
<!-- the content of the main page -->

		<div class="container-fluid" style="min-height:95%; ">


			<div class="row">
				<div class="col-sm-2">
					<!-- left margine -->
				</div>
			<div class="col-sm-8"> <!--center space-->
				<div class="row" style="background-color:#f6f6f6">
						<hr class="my-4">
				</div>

				<div class="row" style="background-color:#f6f6f6">
						<hr class="my-4">
				</div>
					<div class="row" style="background-color:#f6f6f6">
						<hr class="my-4">
						<div class="col-sm-4"> <!--logo image-->
								<img src = "{% static 'imgs/toxinome_logo.jpeg' %}" class="card-img-top" alt = "Responsive image"  />
						</div>
						<hr class="my-4">
					<div class="col-sm-8">
						<div class="row" style="background-color:#f6f6f6">

							<h1>

								Welcome to Toxinome
							<br>
								<small class="text-muted">Bacterial toxin database</small>

							</h1>

						<hr class="my-1">

						</div>
						<div class="row" style="background-color:#f6f6f6">



						<hr class="my-1">
						</div>
						<!--add buttons here-->
						<center>
							<!-- <a class="btn btn-dark btn-sm" href="" role="button">Go to the toxinome</a> -->
							<div class="btn-group" role="group">
								<!-- <button id="btnGroupDrop1" type="button" class="btn btn-dark btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Browse by organism
								</button>
								<div class="dropdown-menu" aria-labelledby="btnGroupDrop1"> -->
									<!-- {% for entry in organism_list %}
										<a class="dropdown-item" href="{% url 'first_app:org_search' entry %}">{{entry}}</a>
									{% endfor %} -->
										<a class="btn btn-dark btn-sm" href="organisms/" role="button">Browse by organism</a>
								<!-- </div> -->

							</div>
							<div class="btn-group">
								<button type="button" class="btn btn-dark btn-sm dropdown-toggle" data-toggle="dropdown">Browse by Pfam <span class="caret"></span></button>
								<ul class="dropdown-menu scrollable-menu" role="menu" style = "height:auto;max-height: 500px;overflow-x: hidden;">
									{% for entry in pfams_list %}
										<li><a class="dropdown-item" href="{% url 'first_app:pfam_search' entry %}">{{entry}}</a></li>
										 {% endfor %}
								</ul>
						</div>

						</center></br>
						<div class="accordion" id="landingPageAccordion">
							<div class="card">
								<div class="card-header" id="headingOne">
									<h2 class="mb-0">
										<button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">

													Toxinome

										</button>
									</h2>

							  </div>

								<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#landingPageAccordion">
									<div class="card-body">
											some explanation for toxinome.</br>
											<!-- <center>
													<img src="{% static 'ecis_web_first_app/static_ims/ecis_fig.png' %}"  class="card-img-top" style='max-height:650px;'alt="img is missing">
											</center>	</br>

									 		some additional explanation -->
									</div>
								</div>
							</div>
							<div class="card">
								<div class="card-header" id="headingTwo">
									<h2 class="mb-0">
										<button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
											Toxinome database info
										</button>
									</h2>
								</div>
								<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#landingPageAccordion">
									<div class="card-body">
											some more text
									</div>
								</div>
							</div>
						</div></br>


					</div>
					</div>
					<div class="row" style="background-color:#f6f6f6">
							<hr class="my-4">
					</div>
				</div>
				<div class="col-sm-2">
					<!-- left margine -->
				</div>
			</div>
		</div>

	</div>
</body>
<footer>
		<div class="container-fluid" style='margin-left:15px'>
		</br>
			<p>Free Use to Academic Non-Profit Institutions. Other Users Please Contact Dr. Asaf Levy : alevy at mail.huji.ac.il</p>
		</div>
</footer>
</html>

templates/includes/htmlsnippet.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>toxin base</title>
	<meta charset="utf-8" />

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  	integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <meta name="viewport" content = "width=device-width, initial-scale=1.0">

	<!-- <style type="text/css">
		html,
		body {
		  height:100%
		}
	</style> -->

</head>
  <body class="body" style="background-color:#e6e6e6">
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="http://www.asaflevylab.com/#"><img src="http://www.asaflevylab.com/labimages/levy_logo.png" style='max-height:40px;'alt="Asaf Levy Lab Logo"></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<div class="navbar-nav">
				<a class="nav-item nav-link active" href="/toxin-base/"> Home </a>
			</div> <!-- /.navbar-nav, left-hand content -->
			<div class="navbar-nav ml-auto">
				<!-- SEARCH BAR -->
				<form class="form-inline" action="/genusearch" method="get">
					<input class="form-control mr-sm-2" name="q" type="text" placeholder="Genus Name" aria-label="Search">
					<button class="btn btn-outline my-2 my-sm-0" type="submit" style="color:green">SEARCH </button>
				</form>
			</div> <!-- /.navbar-nav, right-hand content -->
		</div> <!-- /.navbar-collapse -->
	</nav>
  
		<footer>
		<div class="container-fluid" style='margin-left:15px'>
			<p><a href="https://il.linkedin.com/in/asaf-levy-b87a7145/" target="blank">LinkedIn</a> | <a href="https://twitter.com/AsafLevyHUJI/" target="blank">Twitter</a> | <a href="https://www.facebook.com/asaf.le" target="blank">Facebook</a></p>
		</div>
	</footer>
  </body>
</html>